Controllers/ApplicationJoinedUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class ApplicationJoinedUserController : Controller
    {
        // GET: ApplicationJoinedUser
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobFinderDBEntities db = new JobFinderDBEntities();
            List<APPLICATION> application_date = db.APPLICATIONS.ToList();
            List<USER> user_name = db.USERS.ToList();
            var joinedTable = from a in application_date
                              join u in user_name on a.UserID equals u.UserID
                              where a.PostID == id
                              select new ApplicationJoinedUser { applicationDetails = a, userDetails = u };
            return View(joinedTable);
        }
    }
}

Controllers/POSTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class POSTsController : Controller
    {
        private JobFinderDBEntities db = new JobFinderDBEntities();

        // GET: POSTs/Create
        public ActionResult Create()
        {
            //ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name");
            ViewBag.CompanyID = Session["CompanyID"];
            return View();
        }

        // POST: POSTs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PostID,CompanyID,Salary,Location,Experience,Description")] POST pOST)
        {
            if (ModelState.IsValid)
            {
                db.POSTs.Add(pOST);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", pOST.CompanyID);
            return View(pOST);
        }

        public ActionResult Index(string searchByExp, string searchBySal, string searching)
        {
            if (searchByExp == "0-2")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2).ToList());
                    }
                }
            }
            else if (searchByExp == "3-5")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5).ToList());
                    }
                }
            }
            else if (searchByExp == "6-10")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10).ToList());
                    }
                }
            }
            else
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.ToList());
                    }
                }
            }
        }

        /*Apply method added for CP 2*/
        public ActionResult Apply(int? id)
        {
            if (Session["UserID"] == null)
            {
                ViewBag.Notification = "Please login first!";
            }
            else
            {

Controllers/REVIEWsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class REVIEWsController : Controller
    {
        private JobFinderDBEntities db = new JobFinderDBEntities();

        // GET: REVIEWs
        public ActionResult Index(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            /*
            USER uSER = db.USERS.Find(id);
            if (uSER == null)
            {
                return HttpNotFound();
            }
            */
            COMPANY cOMPANY = db.COMPANies.Find(id);
            if (cOMPANY == null)
            {
                return HttpNotFound();
            }
            return View(db.REVIEWs.Where(x => x.CompanyID == id).ToList());
            //var rEVIEWs = db.REVIEWs.Include(r => r.COMPANY).Include(r => r.USER);
            //return View(rEVIEWs.ToList());
        }

        // GET: REVIEWs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            if (rEVIEW == null)
            {
                return HttpNotFound();
            }
            return View(rEVIEW);
        }

        // GET: REVIEWs/Create
        public ActionResult Create(int? id)
        {
            //ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name");
            //ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name");
            COMPANY cOMPANY = db.COMPANies.Find(id);
            ViewBag.CompanyName = cOMPANY.Name;
            if (Session["UserID"] == null)
            {
                ViewBag.Notification = "Please login first!";
                return View();
            }
            else
            {
                ViewBag.UserID = Session["UserID"];
                ViewBag.CompanyID = id;
                ViewBag.Date = DateTime.Today.ToString("d");
                return View();
            }
        }

        // POST: REVIEWs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ReviewID,CompanyID,UserID,Description,ReviewDate")] REVIEW rEVIEW)
        {
            if (Session["UserID"] == null)
            {
                ViewBag.Notification = "Please login first!";
            }
            else
            {
                if (ModelState.IsValid)
                {
                    db.REVIEWs.Add(rEVIEW);
                    db.SaveChanges();
                    return RedirectToAction("Index", "POSTs");
                }
            }
            //ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rEVIEW.CompanyID);
            //ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rEVIEW.UserID);
            //ViewBag.UserID = Session["UserID"];
            return View(rEVIEW);
        }

        // GET: REVIEWs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            if (rEVIEW == null)
            {
                return HttpNotFound();
            }
            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rEVIEW.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rEVIEW.UserID);
            return View(rEVIEW);
        }

        // POST: REVIEWs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ReviewID,UserID,CompanyID,ReviewDate,Description")] REVIEW rEVIEW)
        {
            if (ModelState.IsValid)
            {
                db.Entry(rEVIEW).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", rEVIEW.CompanyID);
            ViewBag.UserID = new SelectList(db.USERS, "UserID", "Name", rEVIEW.UserID);
            return View(rEVIEW);
        }

        // GET: REVIEWs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            if (rEVIEW == null)
            {
                return HttpNotFound();
            }
            return View(rEVIEW);
        }

        // POST: REVIEWs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            REVIEW rEVIEW = db.REVIEWs.Find(id);
            db.REVIEWs.Remove(rEVIEW);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/COMPANies/CompanyProfile.cshtml
@model JOB_FINDER.Models.COMPANY

@{
    ViewBag.Title = "CompanyProfile";
}

<h2 class="text-center" style="margin-top: 50px; margin-bottom: 50px;">Welcome to your company profile!</h2>

<div class="container">
    <div class="row">
        <div class="col-md-4">
            <ul class="list-group">
                <li class="list-group-item">@Html.ActionLink("See your previous posts?", "SeePrevPostst", new { id = Model.CompanyID })</li>
                <li class="list-group-item">@Html.ActionLink("Create Post", "Create", "POSTs")</li>
                <li class="list-group-item">@Html.ActionLink("Recruit", "Index", "USERs")</li>
                <li class="list-group-item">@Html.ActionLink("Update Password", "UpdatePassword", "COMPANies")</li>
                <li class="list-group-item">@Html.ActionLink("SignOut", "SignOut", "COMPANies")</li>
            </ul>
        </div>
        <div class="col-md-8" style="padding-top: 40px;">
            <div>
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.Name)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Name)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Description)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Description)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Address)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Address)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Phone)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Phone)
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Email)
                    </dt>

                    <dd>
                        @Html.DisplayFor(model => model.Email)
                    </dd>

                    <!--
                        <dt>
                            @Html.DisplayNameFor(model => model.Password)
                        </dt>

                        <dd>
                            @Html.DisplayFor(model => model.Password)
                        </dd>
                -->

                </dl>
            </div>
        </div>
    </div>
</div>

<!--
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.CompanyID })
</p>
-->
<!--Second Checkpoint-->
<!---->

<!--
<div>
    <p><a href="/POSTs/Create" class="btn btn-primary btn-lg">Create Post</a></p>
    <p><a href="/USERs/Index" class="btn btn-primary btn-lg">Recruit</a></p>
</div>
-->

Views/COMPANies/ForgotPassword.cshtml
@model JOB_FINDER.Models.COMPANY

@{
    ViewBag.Title = "Forgot Password";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal" style="color: #1ba94c;">
        <div class="form-group">
            <label style="padding-left: 35px; color: #1ba94c;">Enter the email that was used while creating account</label>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send Mail" class="btn btn-default"  style="background-color: #1ba94c; color: white;"/>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <label>@ViewBag.Notification</label>
            </div>
        </div>
    </div>
}

Views/COMPANies/Login.cshtml
@model JOB_FINDER.Models.TempCompany

@{
    ViewBag.Title = "Login";
    var msg = ViewBag.LoginFailed;
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal" style="color: #1ba94c;">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Login" class="btn btn-default" style="background-color: #1ba94c; color: white;" />
        </div>
    </div>

</div>
}

<div style="margin-left: 250px;">
    <button type="button" class="btn" style="font-size: 17.5px; background-color: white; color: #1ba94c;" onclick="location.href='@Url.Action("ForgotPassword", "COMPANies")'">Forgot Password?</button>
</div>

@if (msg != null)
{
    <p class="text-danger">@msg</p>
}

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/COMPANies/SeeCompanyProfile.cshtml
@model IEnumerable<JOB_FINDER.Models.COMPANY>

@{
    ViewBag.Title = "SeeCompanyProfile";
}

<div style="padding: 50px;">
    <h2 style="margin-bottom: 35px;">This is the Company's Profile</h2>

    @foreach (var item in Model)
    {
        <div>
            <p>
                @Html.DisplayFor(modelItem => item.Name)
            </p>
            <p>
                @Html.DisplayFor(modelItem => item.Phone)
            </p>
            <p>
                @Html.DisplayFor(modelItem => item.Email)
            </p>
            <p>
                @Html.DisplayFor(modelItem => item.Address)
            </p>
            <p>
                @Html.DisplayFor(modelItem => item.Description)
            </p>

            <!--button added for CP 3-->
            <button type="button" class="btn btn-success" onclick="location.href='@Url.Action("Create", "REVIEWs", new { id = item.CompanyID })'">Give Review</button>

            <button type="button" class="btn btn-danger" onclick="location.href='@Url.Action("Index", "REVIEWs", new { id = item.CompanyID })'">See reviews about this company</button>

        </div>
    }
</div>

Views/COMPANies/SeePrevPostst.cshtml
@model IEnumerable<JOB_FINDER.Models.POST>

@{
    ViewBag.Title = "SeePrevPostst";
}

<h2 class="text-center" style="margin-bottom: 35px; margin-top: 35px;">Your previous posts</h2>

<table class="table text-left" style="font-size: 23px;">

    @if (Model.Count() == 0)
    {
        <h2>You haven't posted anything yet!</h2>
    }
    else
    {
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Location)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Experience)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Salary)
            </th>
        </tr>
        foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Location)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Experience)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Salary)
                </td>
                <td>
                    @Html.ActionLink("See Applications", "Index", "ApplicationJoinedUser", new { id = item.PostID }, null)
                </td>
            </tr>
        }
    }

</table>

Views/COMPANies/SignUp.cshtml
@model JOB_FINDER.Models.COMPANY

@{
    ViewBag.Title = "SignUp";
}

<div class="container">
    <div class="row">
        <div class="col-md-6" style="padding-top: 40px;">
            <img style="height: 300px;" src="~/images/onlinelogomaker-092221-2227-9311.svg">
        </div>
        <div class="col-md-6" style="color: #1ba94c;">
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

            <div class="form-horizontal">
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                <div class="form-group">
                    @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Address, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Address, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Address, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Phone, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Phone, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Phone, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    @Html.LabelFor(model => model.ConfirmPassword, htmlAttributes: new { @class = "control-label col-md-2" })
                    <div class="col-md-10">
                        @Html.EditorFor(model => model.ConfirmPassword, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.ConfirmPassword, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Register" class="btn btn-default" style="background-color: #1ba94c; color: white;" />
                    </div>
                    <button type="button" class="btn" style="font-size: 17.5px; background-color: white; color: #1ba94c;" onclick="location.href='@Url.Action("Login", "COMPANies")'">Already have an account?</button>
                </div>

                

            </div>
            }
        </div>
    </div>
</div>

<!--
<div>
    <p><a href="/COMPANies/Login" class="btn btn-primary btn-lg">Login &raquo;</a></p>
</div>
-->

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}