Models/POST.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JOB_FINDER.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class POST
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public POST()
        {
            this.APPLICATIONS = new HashSet<APPLICATION>();
        }
    
        public int PostID { get; set; }
        public int CompanyID { get; set; }
        public int Salary { get; set; }
        public string Location { get; set; }
        public int Experience { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<APPLICATION> APPLICATIONS { get; set; }
        public virtual COMPANY COMPANY { get; set; }
    }
}

Controllers/POSTsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using JOB_FINDER.Models;

namespace JOB_FINDER.Controllers
{
    public class POSTsController : Controller
    {
        private JobFinderDBEntities db = new JobFinderDBEntities();

        // GET: POSTs/Create
        public ActionResult Create()
        {
            //ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name");
            ViewBag.CompanyID = Session["CompanyID"];
            return View();
        }

        // POST: POSTs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "PostID,CompanyID,Salary,Location,Experience,Description")] POST pOST)
        {
            if (ModelState.IsValid)
            {
                db.POSTs.Add(pOST);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.CompanyID = new SelectList(db.COMPANies, "CompanyID", "Name", pOST.CompanyID);
            return View(pOST);
        }

        public ActionResult Index(string searchByExp, string searchBySal, string searching)
        {
            if (searchByExp == "0-2")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 0 && x.Experience <= 2).ToList());
                    }
                }
            }
            else if (searchByExp == "3-5")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 3 && x.Experience <= 5).ToList());
                    }
                }
            }
            else if (searchByExp == "6-10")
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10 && x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Experience >= 6 && x.Experience <= 10).ToList());
                    }
                }
            }
            else
            {
                if (!String.IsNullOrWhiteSpace(searching))
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary >= 5000 && x.Salary <= 20000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 20000 && x.Salary <= 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 50000 && x.Location.Contains(searching)).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.Where(x => x.Location.Contains(searching)).ToList());
                    }
                }
                else
                {
                    if (searchBySal == "5,000-20,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary >= 5000 && x.Salary <= 20000).ToList());
                    }
                    else if (searchBySal == "20,001-50,000")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 20000 && x.Salary <= 50000).ToList());
                    }
                    else if (searchBySal == "50,000+")
                    {
                        return View(db.POSTs.Where(x => x.Salary > 50000).ToList());
                    }
                    else
                    {
                        return View(db.POSTs.ToList());
                    }
                }
            }
        }

        /*Apply method added for CP 2*/
        public ActionResult Apply(int? id)
        {
            if (Session["UserID"] == null)
            {
                ViewBag.Notification = "Please login first!";
            }
            else
            {

Views/POSTs/Apply.cshtml
@{
    ViewBag.Title = "Apply";
}

<h2>Apply</h2>

<div class="form-group">
    <div class="col-md-offset-2 col-md-10">
        <label>@ViewBag.Notification</label>
    </div>
</div>

<p>
    @Html.ActionLink("Back to List", "Index")
</p>

Views/POSTs/Create.cshtml
@model JOB_FINDER.Models.POST

@{
    ViewBag.Title = "Create";
}

<h2 class="text-center" style="margin-top: 50px; margin-bottom: 50px;">Post a vacancy for your company!</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" style="color: white; background-color: #1ba94c;"/>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyID, "CompanyID", htmlAttributes: new { @class = "control-label col-md-2", @style = "visibility:hidden" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CompanyID, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.CompanyID, @style = "visibility:hidden" } })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger", @style = "visibility:hidden" })
            </div>
        </div>

    </div>
}

<div style="padding: 25px;">
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/POSTs/Delete.cshtml
@model JOB_FINDER.Models.POST

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>POST</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COMPANY.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COMPANY.Name)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Views/POSTs/Details.cshtml
@model JOB_FINDER.Models.POST

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>POST</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Salary)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Salary)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Location)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Location)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Experience)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Experience)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.COMPANY.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.COMPANY.Name)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.PostID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/POSTs/Edit.cshtml
@model JOB_FINDER.Models.POST

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>POST</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PostID)

        <div class="form-group">
            @Html.LabelFor(model => model.CompanyID, "CompanyID", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CompanyID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CompanyID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Salary, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Salary, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Salary, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Location, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Location, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Location, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Experience, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Experience, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Experience, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/POSTs/Index.cshtml
@model IEnumerable<JOB_FINDER.Models.POST>

<div class="container">
    <div class="row">
        <div class="col-md-4 col-sm-12" style="border: 0.5px solid #e2e0e0; border-radius: 10px; box-shadow: 1.5px 1.5px 1.5px 1.5px #ded8d8; margin-top: 30px; margin-bottom: 30px; ">
            @using (Html.BeginForm("Index", "POSTs", FormMethod.Get))
            {
                <h3 style="margin-top: 15px">Experience: </h3>
                @Html.RadioButton("searchByExp", "0-2")<p>0-2</p>
                @Html.RadioButton("searchByExp", "3-5")<p>3-5</p>
                @Html.RadioButton("searchByExp", "6-10")<p>6-10</p>
                <h3 style="margin-top: 7.5px">Salary: </h3>
                @Html.RadioButton("searchBySal", "5,000-20,000")<p>5,000-20,000</p>
                @Html.RadioButton("searchBySal", "20,001-50,000")<p>20,001-50,000</p>
                @Html.RadioButton("searchBySal", "50,000+")<p>50,000+</p>
                <h3 style="margin-top: 7.5px">Location: </h3>
                <div style="margin-bottom: 15px">
                    @Html.TextBox("Searching")
                    <input type="submit" value="Filter" class="btn" style="background-color: #1ba94c; color: white;" />
                </div>
            }
        </div>
        <div class="col-md-8 col-sm-12">
            @if (Model.Count() == 0)
            {
                <h2>Nothing Found!</h2>
            }
            else
            {
                foreach (var item in Model)
                {
                    <div class="card" style="margin-top: 15px; margin-bottom: 15px; border: 0.5px solid #e2e0e0; border-radius: 10px; box-shadow: 1.5px 1.5px 1.5px 1.5px #ded8d8; padding: 15px;">
                        <div class="card-header" style="color: #1ba94c; padding: 5px; font-size: 25px;">
                            @Html.DisplayFor(modelItem => item.COMPANY.Name)
                        </div>
                        <div class="card-body" style="padding: 5px;">
                            <h3 class="card-title">@Html.DisplayFor(modelItem => item.Description)</h3>
                            <p class="card-text">@Html.DisplayNameFor(model => model.Location): @Html.DisplayFor(modelItem => item.Location)</p>
                            <p class="card-text">@Html.DisplayNameFor(model => model.Experience): @Html.DisplayFor(modelItem => item.Experience) Years</p>
                            <p class="card-text">@Html.DisplayNameFor(model => model.Salary): @Html.DisplayFor(modelItem => item.Salary) Tk.</p>
                            <!--<a href="#" class="btn btn-success">Apply</a>-->
                            <!--button changed for CP 2-->
                            <button type="button" class="btn" style="background-color: #1ba94c; color: white;" onclick="location.href='@Url.Action("Apply", "POSTs", new { id = item.PostID })'">Apply</button>

                            <button type="button" class="btn btn-primary" onclick="location.href='@Url.Action("SeeCompanyProfile", "COMPANies", new { id = item.CompanyID })'">View Company</button>


                        </div>
                        </div>
                    }
                }
            </div>
        </div>
    </div>